const API_URL = 'https://api.pocket-connect.xyz';

export const topTransaksiListEndpoint = `${API_URL}/kolaborasi`;
export const typePocketEndpoint = `${API_URL}/pocket/tipe`;
export const categoryPocketEndpoint = `${API_URL}/pocket/kategory-count`;
export const topPocketEndpoint = `${API_URL}/pocket/top`;
export const listTopPocketEndpoint = `${API_URL}/pocket/top-creator`;
export const listPocketEndpoint = `${API_URL}/pocket/dashboard`;
export const grafikTransactionEndpoint = `${API_URL}/transaksi/grafik`;
export const topTransaksiDashboardEndpoint = `${API_URL}/transaksi/dashboard-top`;
export const transaksiListDashboardEndpoint = `${API_URL}/transaksi/dashboard`;
export const transaksiListByDayDashboardEndpoint = `${API_URL}/transaksi/dashboard-day`;
export const transaksiListByWeekDashboardEndpoint = `${API_URL}/transaksi/dashboard-week`;
export const transaksiListByMonthDashboardEndpoint = `${API_URL}/transaksi/dashboard-month`;
export const loginEndpoint = `${API_URL}/login`;
export const listUserDetailEndPoint =  `${API_URL}/nasabah`;
export const createUserEndPoint =  `${API_URL}/nasabah`;
export const listUserEndPoint = `${API_URL}/nasabah/dashboard`;
export const authEndpoint = `${API_URL}/check/validate`;
export const grafikPocketEndpoint = `${API_URL}/pocket/grafik`
